# Generated by Django 4.2.5 on 2023-09-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("geometry", models.JSONField()),
                ("icon", models.URLField()),
                ("icon_background_color", models.CharField(max_length=7)),
                ("photos", models.JSONField()),
                ("place_id", models.CharField(max_length=255, unique=True)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
                ("reference", models.CharField(max_length=255)),
                ("types", models.JSONField()),
                ("user_ratings_total", models.IntegerField()),
                ("vicinity", models.TextField()),
                ("business_status", models.CharField(max_length=50)),
            ],
        ),
    ]
