# Generated by Django 4.2.5 on 2023-09-11 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("restaurants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lat", models.DecimalField(decimal_places=6, max_digits=9)),
                ("lng", models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.PositiveIntegerField()),
                ("html_attributions", models.TextField()),
                ("photo_reference", models.CharField(max_length=255)),
                ("width", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="restaurant",
            name="photos",
        ),
        migrations.CreateModel(
            name="Geometry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurants.location",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="restaurant",
            name="geometry",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="restaurants.geometry"
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="photos",
            field=models.ManyToManyField(to="restaurants.photo"),
        ),
    ]
