# Generated by Django 4.2.5 on 2023-09-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "restaurants",
            "0002_location_photo_remove_restaurant_photos_geometry_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
