# Generated by Django 4.2.5 on 2023-09-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_customuser_is_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
